//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karamem0.Capreze.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karamem0.Capreze.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Resize.
        /// </summary>
        public static string ButtonResizeContent {
            get {
                return ResourceManager.GetString("ButtonResizeContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Enable offsets.
        /// </summary>
        public static string LabelEnableOffsetContent {
            get {
                return ResourceManager.GetString("LabelEnableOffsetContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Height:.
        /// </summary>
        public static string LabelHeightContent {
            get {
                return ResourceManager.GetString("LabelHeightContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Width:.
        /// </summary>
        public static string LabelWidthContent {
            get {
                return ResourceManager.GetString("LabelWidthContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _X.
        /// </summary>
        public static string LabelXContent {
            get {
                return ResourceManager.GetString("LabelXContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Y.
        /// </summary>
        public static string LabelYContent {
            get {
                return ResourceManager.GetString("LabelYContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Always On _Top.
        /// </summary>
        public static string MenuItemAlwaysOnTopHeader {
            get {
                return ResourceManager.GetString("MenuItemAlwaysOnTopHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply to Capture Size.
        /// </summary>
        public static string MenuItemApplyToCaptureSizeText {
            get {
                return ResourceManager.GetString("MenuItemApplyToCaptureSizeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto _Resize.
        /// </summary>
        public static string MenuItemAutoResizeHeader {
            get {
                return ResourceManager.GetString("MenuItemAutoResizeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MenuItemExitHeader {
            get {
                return ResourceManager.GetString("MenuItemExitHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuItemFileHeader {
            get {
                return ResourceManager.GetString("MenuItemFileHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _GitHub.
        /// </summary>
        public static string MenuItemGitHubText {
            get {
                return ResourceManager.GetString("MenuItemGitHubText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuItemHelpHeader {
            get {
                return ResourceManager.GetString("MenuItemHelpHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MenuItemOptionsHeader {
            get {
                return ResourceManager.GetString("MenuItemOptionsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Window to Top.
        /// </summary>
        public static string MenuItemShowWindowToTopText {
            get {
                return ResourceManager.GetString("MenuItemShowWindowToTopText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        public static string TextBlockActualSizeText
        {
            get
            {
                return ResourceManager.GetString("TextBlockActualSizeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capture Size.
        /// </summary>
        public static string TextBlockCaptureSizeText {
            get {
                return ResourceManager.GetString("TextBlockCaptureSizeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string TextBlockHeightText {
            get {
                return ResourceManager.GetString("TextBlockHeightText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offset:.
        /// </summary>
        public static string TextBlockOffsetText {
            get {
                return ResourceManager.GetString("TextBlockOffsetText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PID:.
        /// </summary>
        public static string TextBlockPidText {
            get {
                return ResourceManager.GetString("TextBlockPidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string TextBlockWidthText {
            get {
                return ResourceManager.GetString("TextBlockWidthText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capreze.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
