//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karamem0.Capreze.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karamem0.Capreze.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutMenuItemText
        {
            get
            {
                return ResourceManager.GetString("AboutMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle
        {
            get
            {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        public static string ActualSizeTextBlockText
        {
            get
            {
                return ResourceManager.GetString("ActualSizeTextBlockText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Always On _Top.
        /// </summary>
        public static string AlwaysOnTopMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("AlwaysOnTopMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply to Capture _Size.
        /// </summary>
        public static string ApplyToCaptureSizeMenuItemText
        {
            get
            {
                return ResourceManager.GetString("ApplyToCaptureSizeMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto _Resize.
        /// </summary>
        public static string AutoResizeMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("AutoResizeMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capture Size.
        /// </summary>
        public static string CaptureSizeTextBlockText
        {
            get
            {
                return ResourceManager.GetString("CaptureSizeTextBlockText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Enable offsets.
        /// </summary>
        public static string EnableLabelOffsetContent
        {
            get
            {
                return ResourceManager.GetString("EnableLabelOffsetContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorWindowTitle
        {
            get
            {
                return ResourceManager.GetString("ErrorWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ExitMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("ExitMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("FileMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _GitHub.
        /// </summary>
        public static string GitHubMenuItemText
        {
            get
            {
                return ResourceManager.GetString("GitHubMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Height:.
        /// </summary>
        public static string HeightLabelContent
        {
            get
            {
                return ResourceManager.GetString("HeightLabelContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightTextBlockText
        {
            get
            {
                return ResourceManager.GetString("HeightTextBlockText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("HelpMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch _Snipping Tool.
        /// </summary>
        public static string LaunchSnippingToolMenuItemText
        {
            get
            {
                return ResourceManager.GetString("LaunchSnippingToolMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capreze.
        /// </summary>
        public static string MainWindowTitle
        {
            get
            {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M_aximize Window.
        /// </summary>
        public static string MaximizeWindowMenuItemText
        {
            get
            {
                return ResourceManager.GetString("MaximizeWindowMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M_inimize Window.
        /// </summary>
        public static string MinimizeWindowMenuItemText
        {
            get
            {
                return ResourceManager.GetString("MinimizeWindowMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offset:.
        /// </summary>
        public static string OffsetTextBlockText
        {
            get
            {
                return ResourceManager.GetString("OffsetTextBlockText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonContent
        {
            get
            {
                return ResourceManager.GetString("OkButtonContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to open URL..
        /// </summary>
        public static string OpenUriErrorText
        {
            get
            {
                return ResourceManager.GetString("OpenUriErrorText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string OptionsMenuItemOHeader
        {
            get
            {
                return ResourceManager.GetString("OptionsMenuItemOHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PID:.
        /// </summary>
        public static string PidTextBlockText
        {
            get
            {
                return ResourceManager.GetString("PidTextBlockText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Resize.
        /// </summary>
        public static string ResizeButtonContent
        {
            get
            {
                return ResourceManager.GetString("ResizeButtonContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Show Window to Top.
        /// </summary>
        public static string ShowWindowToTopMenuItemText
        {
            get
            {
                return ResourceManager.GetString("ShowWindowToTopMenuItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Width:.
        /// </summary>
        public static string WidthLabelContent
        {
            get
            {
                return ResourceManager.GetString("WidthLabelContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string WidthTextBlockText
        {
            get
            {
                return ResourceManager.GetString("WidthTextBlockText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _X.
        /// </summary>
        public static string XLabelContent
        {
            get
            {
                return ResourceManager.GetString("XLabelContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Y.
        /// </summary>
        public static string YLabelContent
        {
            get
            {
                return ResourceManager.GetString("YLabelContent", resourceCulture);
            }
        }
    }
}
