name: Build source

description: This GitHub Action builds sources and uploads its artifacts.

runs:
  using: composite
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.x
    - name: Restore project
      shell: pwsh
      run: dotnet restore source/Karamem0.Capreze.sln
    - name: Build source
      shell: pwsh
      run: |
        dotnet publish `
          source/Karamem0.Capreze/Karamem0.Capreze.csproj `
          -c Release `
          -o artifact/capreze `
          -p:Version=${{env.BUILD_VERSION}}.${{github.run_number}} `
          -p:FileVersion=${{env.BUILD_VERSION}}.${{github.run_number}}
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: capreze
        path: artifact/capreze
        include-hidden-files: true
    - name: Build source (x64)
      shell: pwsh
      run: |
        dotnet publish `
          source/Karamem0.Capreze/Karamem0.Capreze.csproj `
          -c Release `
          -o artifact/capreze_win-x64 `
          -r win-x64 `
          --self-contained `
          -p:Version=${{env.BUILD_VERSION}}.${{github.run_number}} `
          -p:FileVersion=${{env.BUILD_VERSION}}.${{github.run_number}} `
          -p:PublishSingleFile=true `
          -p:IncludeAllContentForSelfExtract=true
    - name: Upload artifact (x64)
      uses: actions/upload-artifact@v7
      with:
        name: capreze_win-x64
        path: artifact/capreze_win-x64
        include-hidden-files: true
    - name: Build source (x86)
      shell: pwsh
      run: |
        dotnet publish `
          source/Karamem0.Capreze/Karamem0.Capreze.csproj `
          -c Release `
          -o artifact/capreze_win-x86 `
          -r win-x86 `
          --self-contained `
          -p:Version=${{env.BUILD_VERSION}}.${{github.run_number}} `
          -p:FileVersion=${{env.BUILD_VERSION}}.${{github.run_number}} `
          -p:PublishSingleFile=true `
          -p:IncludeAllContentForSelfExtract=true
    - name: Upload artifact (x86)
      uses: actions/upload-artifact@v7
      with:
        name: capreze_win-x86
        path: artifact/capreze_win-x86
        include-hidden-files: true
    - name: Setup WiX Toolset
      shell: pwsh
      run: |
        dotnet tool install --global wix --version 5.0.2
        wix extension add -g WixToolset.UI.wixext/5.0.2
    - name: Build source (Installer)
      shell: pwsh
      run: |
        dotnet run `
          Karamem0.Capreze.Installer.csproj `
          -p:Version=${{env.BUILD_VERSION}}.${{github.run_number}} `
          -p:FileVersion=${{env.BUILD_VERSION}}.${{github.run_number}}
      working-directory: source/Karamem0.Capreze.Installer
    - name: Update README.txt
      shell: pwsh
      run: |
        $content = Get-Content -Path assets/README.txt
        $content = $content -Replace "{{BUILD_VERSION}}", "${{env.BUILD_VERSION}}"
        Out-File -FilePath artifact/capreze_installer/README.txt -InputObject $content -Encoding UTF8
    - name: Upload artifact (Installer)
      uses: actions/upload-artifact@v7
      with:
        name: capreze_installer
        path: artifact/capreze_installer
        include-hidden-files: true
