name: Deploy to Azure

description: This GitHub Action deploys built artifacts to Azure.

runs:
  using: composite
  steps:
    - name: Download artifatcs
      uses: actions/download-artifact@v8
      with:
        name: capreze_installer
        path: artifact
    - name: Provision artifact
      shell: pwsh
      run: Copy-Item -Path artifact/capreze.msi -Destination capreze_${{env.BUILD_VERSION}}.msi
    - name: Connect to Azure
      uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c
      with:
        creds: ${{env.AZURE_CREDENTIALS}}
    - name: Deploy MSI package
      uses: azure/cli@9eb25b8360668fb0ecbafa808d40e2197b2f5f52
      with:
        inlineScript: |
          az storage blob upload \
            --file capreze_${{env.BUILD_VERSION}}.msi \
            --account-name ${{env.AZURE_STORAGE_ACCOUNT_NAME}} \
            --container-name msi \
            --auth-mode login \
            --overwrite
