<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageVersion Include="TinyMapper" Version="3.0.3" />
    <PackageVersion Include="WixSharp" Version="1.26.0" />
    <PackageVersion Include="WixSharp.wix.bin" Version="3.14.1" />
  </ItemGroup>

</Project>
