name: Build source

on: workflow_call

permissions: {}

jobs:
  run:
    name: Run
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore project
        run: dotnet restore source/Karamem0.Capreze.sln
      - name: Build source
        shell: pwsh
        run: |
          dotnet publish `
            source/Karamem0.Capreze/Karamem0.Capreze.csproj `
            -c Release `
            -o artifact/capreze `
            -p:Version=${{vars.BUILD_VERSION}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capreze
          path: artifact/capreze
      - name: Build source (x64)
        shell: pwsh
        run: |
          dotnet publish `
            source/Karamem0.Capreze/Karamem0.Capreze.csproj `
            -c Release `
            -o artifact/capreze_win-x64 `
            -r win-x64 `
            --self-contained `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:PublishSingleFile=true `
            -p:IncludeAllContentForSelfExtract=true
      - name: Upload artifact (x64)
        uses: actions/upload-artifact@v4
        with:
          name: capreze_win-x64
          path: artifact/capreze_win-x64
      - name: Build source (x86)
        shell: pwsh
        run: |
          dotnet publish `
            source/Karamem0.Capreze/Karamem0.Capreze.csproj `
            -c Release `
            -o artifact/capreze_win-x86 `
            -r win-x86 `
            --self-contained `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:PublishSingleFile=true `
            -p:IncludeAllContentForSelfExtract=true
      - name: Upload artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: capreze_win-x86
          path: artifact/capreze_win-x86
      - name: Build msi
        run: |
          dotnet build `
            source/Karamem0.Capreze.Installer/Karamem0.Capreze.Installer.csproj `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}}
      - name: Upload msi
        uses: actions/upload-artifact@v4
        with:
          name: capreze_installer
          path: artifact/capreze.msi
