name: Deploy to GitHub Release

on: workflow_call

permissions:
  contents: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Download artifatcs
        uses: actions/download-artifact@v4
        with:
          path: artifact
      - name: Provision artifact
        shell: pwsh
        run: |
          Copy-Item -Path artifact/capreze_installer/capreze.msi -Destination capreze_${{vars.BUILD_VERSION}}.msi
          Compress-Archive -Path artifact/capreze/* -DestinationPath capreze_${{vars.BUILD_VERSION}}.zip
          Compress-Archive -Path artifact/capreze_win-x64/* -DestinationPath capreze_${{vars.BUILD_VERSION}}_win-x64.zip
          Compress-Archive -Path artifact/capreze_win-x86/* -DestinationPath capreze_${{vars.BUILD_VERSION}}_win-x86.zip
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: |
            capreze_${{vars.BUILD_VERSION}}.msi
            capreze_${{vars.BUILD_VERSION}}.zip
            capreze_${{vars.BUILD_VERSION}}_win-x64.zip
            capreze_${{vars.BUILD_VERSION}}_win-x86.zip
