name: Trigger on main

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build-source:
    name: Build source
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Build source
        uses: ./.github/actions/build-source
        env:
          BUILD_VERSION: ${{vars.BUILD_VERSION}}
