name: Trigger on tags

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build-source:
    name: Build source
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Build source
        uses: ./.github/actions/build-source
        env:
          BUILD_VERSION: ${{vars.BUILD_VERSION}}
  deploy-to-azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build-source
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Deploy to Azure
        uses: ./.github/actions/deploy-to-azure
        env:
          AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
          AZURE_STORAGE_ACCOUNT_NAME: ${{vars.AZURE_STORAGE_ACCOUNT_NAME}}
          BUILD_VERSION: ${{vars.BUILD_VERSION}}
  deploy-to-github-release:
    name: Deploy to GitHub Release
    runs-on: ubuntu-latest
    needs: build-source
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Deploy to GitHub Release
        uses: ./.github/actions/deploy-to-github-release
        env:
          BUILD_VERSION: ${{vars.BUILD_VERSION}}
