on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*.*.*

env:
  BUILD_VERSION: '1.11.0'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore project
        run: dotnet restore source/Karamem0.Capreze.sln
      - name: Build source
        shell: pwsh
        run: |
          dotnet publish source/Karamem0.Capreze/Karamem0.Capreze.csproj `
            -c Release `
            -o artifact/capreze `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: capreze
          path: artifact/capreze
      - name: Build source (x64)
        shell: pwsh
        run: |
          dotnet publish source/Karamem0.Capreze/Karamem0.Capreze.csproj `
            -c Release `
            -o artifact/capreze_win-x64 `
            -r win-x64 `
            --self-contained `
            -p:Version=${{env.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{env.BUILD_VERSION}}.${{github.run_number}} `
            -p:PublishSingleFile=true `
            -p:IncludeAllContentForSelfExtract=true
      - name: Upload artifact (x64)
        uses: actions/upload-artifact@v4
        with:
          name: capreze_win-x64
          path: artifact/capreze_win-x64
      - name: Build source (x86)
        shell: pwsh
        run: |
          dotnet publish source/Karamem0.Capreze/Karamem0.Capreze.csproj `
            -c Release `
            -o artifact/capreze_win-x86 `
            -r win-x86 `
            --self-contained `
            -p:Version=${{env.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{env.BUILD_VERSION}}.${{github.run_number}} `
            -p:PublishSingleFile=true `
            -p:IncludeAllContentForSelfExtract=true
      - name: Upload artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: capreze_win-x86
          path: artifact/capreze_win-x86
      - name: Build msi
        run: |
          dotnet build source/Karamem0.Capreze.Installer/Karamem0.Capreze.Installer.csproj `
            -p:Version=${{env.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{env.BUILD_VERSION}}.${{github.run_number}}
      - name: Upload msi
        uses: actions/upload-artifact@v4
        with:
          name: capreze_installer
          path: artifact/capreze.msi
  release:
    needs: build
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: capreze
          path: capreze
      - name: Download artifact (msi)
        uses: actions/download-artifact@v4
        with:
          name: capreze_installer
          path: capreze_installer
      - name: Download artifact (x64)
        uses: actions/download-artifact@v4
        with:
          name: capreze_win-x64
          path: capreze_win-x64
      - name: Download artifact (x86)
        uses: actions/download-artifact@v4
        with:
          name: capreze_win-x86
          path: capreze_win-x86
      - name: Provision artifact
        shell: pwsh
        run: |
          Copy-Item -Path capreze_installer/capreze.msi -Destination capreze_${{env.BUILD_VERSION}}.msi
          Compress-Archive -Path capreze/* -DestinationPath capreze_${{env.BUILD_VERSION}}.zip
          Compress-Archive -Path capreze_win-x64/* -DestinationPath capreze_${{env.BUILD_VERSION}}_win-x64.zip
          Compress-Archive -Path capreze_win-x86/* -DestinationPath capreze_${{env.BUILD_VERSION}}_win-x86.zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: |
            capreze_${{env.BUILD_VERSION}}.msi
            capreze_${{env.BUILD_VERSION}}.zip
            capreze_${{env.BUILD_VERSION}}_win-x64.zip
            capreze_${{env.BUILD_VERSION}}_win-x86.zip
      - name: Connect to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy MSI package
        uses: azure/cli@v2
        with:
          inlineScript: az storage blob upload --file capreze_${{env.BUILD_VERSION}}.msi --account-name ${{secrets.AZURE_STORAGE_ACCOUNT_NAME}} --container-name msi --auth-mode login
